### ISSUE TITLE
List symbol is `<` instead of `>`

### ISSUE THREAD

**Issue by amuehli** [LiaScript/LiaScript-Exporter#22]
Hi André,
thanks for the update on the exporter. Testing it I found that the symbol used to render lists in SCORM-Modules is `<` instead of `>` like so:
  < This is an item in a list
  < And this is another item
which looks odd (at least to me) and has not been so before. Is this a bug or a design decision?
Btw the same goes for liascript-preview.
See also the attached files:
[liascript_test_new-exporter-list-symbol.md](https://github.com/LiaScript/LiaScript-Exporter/files/8097538/liascript_test_new-exporter-list-symbol.md)
[liascript_test_new-exporter-list-symbol.zip](https://github.com/LiaScript/LiaScript-Exporter/files/8097539/liascript_test_new-exporter-list-symbol.zip)
Thanks
Andreas

**Comment by andre-dietrich** [comment]
Hi Andreas,

yeah, this is not a bug, it was a design decision, but you are not the one to complain. This list symbol is used everywhere in LiaScript. Maybe it would be a good choice to preserve the semantics for the list-characters.

```markdown
+ positive
+ ...
- negative
- ....
* neutral
* ...
```

And preserve these symbols also within the rendered list. Such that the user could decide, if he or she prefers dashes, pluses, or dots ... This would diverge from the Markdown standard, but I think it could be a benefit...

@SebastianZug @amuehli what is your opinion in this case :-)

**Comment by amuehli** [comment]
Hi André,
Thanks for answering so quickly.
I have to admit that I find it tempting to have more control (and being able, as you suggested, to chose the symbol). But from an RDM and OER (and in general interoperability) perspective I would argue that as few alterations from standard (probably github flavored?) markdown as possible would be best and that deviations should only occur by adding something (adhering to markdown logic if possible) - as you did beautifully with combining !image and ?audio to !?video - but not by changing standard md (so that the md-files used for liascript can also be used with a standard md interpreter with little to no changes and unexpected behaviour).
I am not sufficiently versed in md to judge whether the alteration you described would meet with this reasoning but my understanding is that -, + and * are pretty much interchangeable but should not be mixed (at least in the same list) - so it probably could work?
From a purely design perspective I personally prefer the dot as unordered list symbol (which has the additional benefit to allow for two differerent symbols for two levels with full and empty), but also liked the somewhat distinct liascript-look with the ">". But the reversed "<" is still confusing for my eyes. ">" points to the list item, but "<" just seems to point in the wrong direction.
But I certainly do not want to incite a design war just because of my very personal aesthetics and can live with any decision - and btw I assume there are much more pressing things to do and consider so please feel very free to simply ignore my ramblings on this :-)

**Comment by andre-dietrich** [comment]
We switched to the github flavored style for lists... These changes have been committed and will be released with the next update ;-) ... 

- dot
  - circle
    - square
      - square ...

https://github.com/LiaScript/LiaScript/pull/87/commits/2015bb3da19bb8d6371aef230981470e4d389f0c

**Comment by amuehli** [comment]
Great news, thanks a lot!
