### ISSUE TITLE
Frage zur SCORM Startdatei

### ISSUE THREAD

**Issue by rfuehrer** [LiaScript/LiaScript-Exporter#31]
Hallo André,

ich habe eine Scorm2004 Datei erstellt und v ersuche diese über SCORM Cloud zu importieren. Der Import klappt, allerdings wird folgende Anzeige dargestellt und ich weiss nicht, welche Eingabe möglich ist bzw. wie diese verhindert werden kann? Ist Dir/Euch das bekannt?

![7856](https://user-images.githubusercontent.com/25303664/219970658-3050b9c1-d524-413b-92f3-1ca08564e0dd.png)

**Comment by andre-dietrich** [comment]
Ja, dass Problem hatten wir bei ILIAS auch. In dem Fall unterstützte das LMS nicht den vollständigen SCORM-Standard und kannte nicht den richtigen Anfangsparameter, mit dem man URL Parameter übergeben konnte ...

Hier gibt es einen Workaround:

``` bash
$ liaex --help
...
--scorm-iframe             use an iframe, when a SCORM starting parameter is not working
...
```

Einfach nochmal das Projekt konvertieren mit dem zusätzlichen Parameter `--scorm-iframe`, der Rest sollte bleiben ... Ich hoffe das hilft?
