### ISSUE TITLE
--scorm-alwaysActive - required undescribed key

### ISSUE THREAD

**Issue by alexeygrinevich** [LiaScript/LiaScript-Exporter#36]
When exporting as SCORM package I found that --scorm-masteryScore 100 has no effect until --scorm-alwaysActive is also specified. 

--scorm-alwaysActive is not mentioned by liaex --help

I hope that helps others.

**Comment by andre-dietrich** [comment]
Thanks @alexeygrinevich ... what LMS are you using?

The exporter has been updated. Previously the SCORM export was using relying on the `cmi.core.lesson_mode` value, which defines the possible modes (“browse”, “normal”, “review”). Some LMS do not set this value and therefore results have not been stored. Now, if this value is not set, it is assumed to be in normal mode and results should be stored and rated ... I hope this fixes your problem ...

**Comment by alexeygrinevich** [comment]
Hi Andre,

We use LearnWorlds LMS. It understands exported SCORM package well, except a couple of issues that I believe on their side. I've sent all details to their dev team and wait for response. 
If showing previous results when returning to a package is not crucial, then LearnWorlds may be said to be already compatible with Lia's SCORM.
If I hear from them and it start working, I'll update you here.

Overall, thank you for all efforts and this great toolset.

**Comment by alexeygrinevich** [comment]
So this one may be closed.
