### ISSUE TITLE
Comment in macro

### ISSUE THREAD

**Issue by alexeygrinevich** [LiaScript/LiaScript-Exporter#38]
I have a quizz like:

[[!]]
<script>
// Something here
</script>

And I want to make a macro with it. Right now I found no way to have  within a macro because macro is inside <!-- comment by itself. Is there an alternative way besides declaring a <!-- for the same? Or maybe some way to escape <!-- for this purpose.

**Comment by andre-dietrich** [comment]
Hi, do you mean something like this:

![image](https://github.com/LiaScript/LiaScript-Exporter/assets/3089101/c4a73d72-913b-4e11-8dea-3bdb789860ac)

basically it is possible to use macros with comments within ... LiaScript will parse it correctly, looking only onto the the main comment-tags and greedy consume all comments within. But, other Markdown-renderers will not display it as expected...

Currently there is no escaping for HTML-comments, but in such cases you could also think of using common HTML-tags with some custom styling to achieve the same result:

![image](https://github.com/LiaScript/LiaScript-Exporter/assets/3089101/2d74f217-c4b2-4fc0-a32e-7a8f3037b7d1)

not sure if this solves your problem ;-) ...

**Comment by alexeygrinevich** [comment]
Thank you for explanations and examples! I'm asking because I was getting errors when I was trying it so I thought it is unsupported.

I've just tried your example [here](https://liascript.github.io/LiveEditor/?/edit/y384b7xOcNDiIhqS12UilQqY)

I typed it exactly as you do, but the result I'm seeing is different:
![image](https://github.com/LiaScript/LiaScript-Exporter/assets/25929131/16d156ab-5a2a-47b1-bd93-d4ebef9d5acc)

Are there any options in LiveEditor to have it working exactly as it works in your case?

Br/Alexey

**Comment by andre-dietrich** [comment]
You can share your examples via the snapshot-url option, this way the entire course will be included into the url ...
Here is my example ... 

https://liascript.github.io/LiveEditor/?/show/code/H4sIAAAAAAAAA1WOwQ6DIBBE7/sVW73YBIxcjW34gd56BwrbSCJiFi79+6pJDz1O3szLTBcpAXRynvOI2q25zsTmzJ1SSlg92Ove+CMAz5nwHblU3By7RJUYY0E9AEy7Ekv9LHRrfF4yj0yhQSnv56qQz2s4y2r30hoADgZti49DXn5/OusEvmIVmDKTQGN8TtsSvasUjBHY9729fgHNs5CfwgAAAA==

From your example, it looks as if something is not fine with the backticks ... It seems to separate parameters by commas and thus only show a as the first parameter, the other ones are not used ...

**Comment by alexeygrinevich** [comment]
Ah, I've got the point!

```
@macro: @another_macro(111,`@0`) - works
@macro: @another_macro(111, `@0`) - fails
```

Just good to know, it is better to avoid whitespaces when passing macro params.
